name: Update Stable Tag

on:
  workflow_dispatch:
    inputs:
      new_tag:
        description: 'New tag to point "stable" to'
        required: true

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update Stable Tag
        run: |
          git tag -f stable ${{ github.event.inputs.new_tag }}
          git push -f origin stable
